### ISSUE TITLE
What is this feature called?

### ISSUE THREAD

**Issue by Jameskmonger** [iarna/node-qw#1]
Hi @iarna,

I noticed that I can do

    qw`hello there`

but not

    qw"hello there"

Why can I do it with template strings and not normal strings? What is this feature called?

**Comment by Jameskmonger** [comment]
These are called "tagged template literals" and you can [read about them on MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Template_literals#Tagged_template_literals).

**Comment by iarna** [comment]
I should probably add that to the docs!
